# "Compose is a tool for defining and running multi-container Docker applications. To learn more about Compose refer to the following documentation:"

# source: 
# https://docs.docker.com/compose/rails/#define-the-project

version: '3.2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - $PWD:/sunroofer
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      