# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cf1b553ac318cbdc3f6471517c3fc2048a2cef040dc7868ac1e3f7fc38f1cb5d953a85d2945d8468cc130051f9278d1cba1e2d5dd422620fe57f85d4d83c6b60

test:
  secret_key_base: 46f1adc88a4222a020438a9efa20142cb6dcd738ea64547cee3d6506f19c9f172266afc94d55baef7c2c882c11f7688e5accdaff019913bb6870640e61a28487

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
